Issue4 app navigation
Joelgh1/agregador-rss pull request #16
Opened 2022-11-30 18:22 UTC by Joelgh1

## Description de la tarea

Navegación entre pantallas con menú principal

## ¿Cómo se ha implementado?

En la main activity se establece el fragmento del feed como inicio y debido a la distribución del menú que escogí el elemento que aparece seleccionado no se corresponde con el fragmento mostrado. Para solucionar esto en el método onStart cambio el elemento del menú seleccionado.
Las actions creadas en el nav_graph son para la navegación segura.
El menú se asigna al bottom navigation en la propia vista porque va a ser común a toda la aplicación.

## Keywords

navigation, fragment, menu, safe args

## Screenshots or Video

https://user-images.githubusercontent.com/107778199/204877705-bea88bc1-154e-47c5-ae69-913b7e6e3fef.mp4

## Objetivos

## Criterios de Evaluación

2022-11-30 23:12 UTC, josem-perram requested changes
@Joelgh1 revisa los comentarios de la PR

2022-11-30 23:12 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/MainActivity.kt
> +                R.id.page_1 -> navigateToManagement()
page_1, page_X no es un namings muy descriptivo. ¿Que pasa si te pido añadir un nuevo botón a la izquierda del botón home? ¿en la posición 2? sería la page_2 y no coincidiría con lo que tienes ahora. Un ejemplo correcto sería:
option_user_rss, option_feed_rss, option_profile....

2022-11-30 23:12 UTC, josem-perram commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
Al usar ConstraintsLayout, deberíamos anular el width con 0dp y usar el start y end del parent.

2022-11-30 23:12 UTC, josem-perram commented on app/src/main/res/menu/bottom_navigation_menu.xml
> +        android:id="@+id/page_1"
El naming no es descriptivo.

2022-11-30 23:12 UTC, josem-perram commented on app/src/main/res/menu/bottom_navigation_menu.xml
> +        android:id="@+id/page_2"
El naming no es descriptivo.

2022-11-30 23:12 UTC, josem-perram commented on app/src/main/res/menu/bottom_navigation_menu.xml
> +        android:id="@+id/page_3"
El naming no es descriptivo.

2022-11-30 23:12 UTC, josem-perram commented on app/src/main/res/navigation/nav_graph.xml
> +    <action
EStos actions al ser globales dentro de la actividad es mejor ubicarlos arriba por si se añaden más fragments.

2022-11-30 23:31 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/MainActivity.kt
> +                R.id.page_1 -> navigateToManagement()
Estoy de acuerdo con eso, no me di cuenta en su momento lo arreglare ahora

2022-11-30 23:32 UTC, Joelgh1 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
Haré el cambio, sin embargo me gustaría saber si hay alguna diferencia en el comportamiento entre las dos formas de hacerlo

2022-11-30 23:33 UTC, Joelgh1 commented on app/src/main/res/navigation/nav_graph.xml
> +    <action
Ok, tiene sentido

2022-12-13 14:31 UTC, alvarogo1998 approved these changes
Buena PR, por lo que veo funciona todo. :ok_hand:

2022-12-16 15:23 UTC, josem-perram approved these changes
🚀

2023-01-09 18:08 UTC, merged