Issue5 rss form
Joelgh1/agregador-rss pull request #17
Opened 2022-11-30 18:41 UTC by Joelgh1

## Description de la tarea

Crear un formulario para agregar rss

## ¿Cómo se ha implementado?

Primero he tenido que modificar el método create para que devuelva un either y asi tener feedback de la operacion.
El boton de cancelar simplemente vuelve a la pantalla anterior es decir el fragmento de management.
El boton de guardar llama al método para guardar rss del viewmodel, este actualiza el UiModel en el que se guarda si se guarda o recibe un error, dependiendo del contenido del either.
He decidido que devuelva un valor booleano para facilitar el código que tendra la vista. Un simple if para decidir que mensaje enviará el snackbar.
Además la toolbar se incluye sin menú en cada fragmento porque la única que tendrá opciones es la de management y se le aplica el menú en el propio fragmento.

## Keywords

formulario, bottom view, presentation, navigation

## Screenshots or Video

https://user-images.githubusercontent.com/107778199/204878708-36bc5e93-d090-4ebe-94f0-b2710713b9eb.mp4

## Objetivos

## Criterios de Evaluación

2022-11-30 23:33 UTC, josem-perram requested changes
Hay cosas importantes que cambiar y que debemos seguir trabajando en próximos proyectos. Por favor, revisa los comentarios.

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/rss_management/data/local/XmlLocalDataSource.kt
> +        return if(sharedPrefs.contains(rss.name) ||
@Joelgh1 en el ticket no se pedía validación de datos, revisa la sección Nota. Si el nombre del RSS ya existía previamente, se sobreescribe. Con este código:
```
 sharedPrefs.edit {
                putString(rss.name, serializer.toJson(rss, Rss::class.java))
            }
            return if(sharedPrefs.contains(rss.name)){
                true.right()
            }else{
                ErrorApp.DataError().left()
            }
```
Lo que estás haciendo es, insertar en SharefPreferences y luego validar que SharefPreferente lo ha insertado. En este caso no es nuestra responsabilidad comprobar si esta librería funciona bien o no. 

En este ocasión, yo hubiera envuelto todo el código en un try catch por si da un error de permisos o algo así y si entra en el catch, devolver Either.left.

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormBottomSheet.kt
> +                showSnackBar(true)
Por qué muestras el snackbar tras pulsar el botón saveRssButton??

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormBottomSheet.kt
> +            Snackbar.make(
Aquí duplicas mucho código, por qué no crear una función de extensión tipo:

```
fun View.showSnackBar(text: String){
         Snackbar.make(
                this,
                text,
                Snackbar.LENGTH_SHORT
            ).show()
)
```
Y se usaría así:
```
if (isSuccess) 
  requireActivity().findViewById(R.id.nav_host_fragment).showSnackBar(getString(R.string.save_success))
else {
 requireActivity().findViewById(R.id.nav_host_fragment).showSnackBar(getString(R.string.save_error))
}

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormBottomSheet.kt
> +class AddRssFormBottomSheet : BottomSheetDialogFragment() {
Sólo los casos de uso comienzan por un verbo.

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormViewModel.kt
> +class AddRssFormViewModel(private val saveRssUseCase: SaveRssUseCase) : ViewModel() {
Sólo los casos de uso comienzan por un Verbo

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormViewModel.kt
> +                    is Either.Left -> publisher.postValue(
Truco: algo más corto podría ser:
```
val response = saveRssUseCase.execute(name, url)
publisher.postValue(UIModel(response.isRight()))
```

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/res/layout/bottom_sheet.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
el nombre bottom_sheet.xml no es descriptivo. ¿Qué pasa si tienes más bottom_sheets?

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/res/layout/bottom_sheet.xml
> +        android:hint="Nombre de la rss"
No usamos strings.xml para la internacionalización.

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/res/layout/bottom_sheet.xml
> +        android:hint="Url de la rss"
No usamos strings.xml para la internacionalización.

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/res/layout/fragment_rss_feed.xml
> +    <androidx.appcompat.widget.Toolbar
Cuidadin que no se pedía Toolbar en el ticket.

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/res/layout/fragment_profile.xml
> +    <androidx.appcompat.widget.Toolbar
Cuidadin que no se pedía toolbar en el ticket.

2022-11-30 23:33 UTC, josem-perram commented on app/src/main/res/menu/management_tool_bar_menu.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android"
sugerencia naming: menu_management

2022-11-30 23:38 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormBottomSheet.kt
> +class AddRssFormBottomSheet : BottomSheetDialogFragment() {
Ok, ahora lo soluciono

2022-11-30 23:41 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormViewModel.kt
> +                    is Either.Left -> publisher.postValue(
Para hacerlo así tendría que devolver un valor booleano, pero al ser un either lo que devuelve eso no es viable

2022-11-30 23:41 UTC, Joelgh1 commented on app/src/main/res/layout/bottom_sheet.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Haré el cambio

2022-11-30 23:42 UTC, Joelgh1 commented on app/src/main/res/layout/bottom_sheet.xml
> +        android:hint="Nombre de la rss"
Se me olvido meterlo en strings, ahora lo corrijo

2022-11-30 23:43 UTC, Joelgh1 commented on app/src/main/res/layout/fragment_profile.xml
> +    <androidx.appcompat.widget.Toolbar
De hecho sí, es el primer check

2022-11-30 23:48 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/data/local/XmlLocalDataSource.kt
> +        return if(sharedPrefs.contains(rss.name) ||
Ok, hare el cambio

2022-11-30 23:52 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormBottomSheet.kt
> +                showSnackBar(true)
Eso estaba para hacer pruebas porque estaba teniendo problemas con el observer, me di cuenta más adelante y lo quite

2022-11-30 23:54 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/presentation/AddRssFormBottomSheet.kt
> +            Snackbar.make(
No lo pensé en su momento, más adelante cree una función de extensión pero como la hice para fragment no me servía para este caso al no permitir buscar una vista. Lo implementaré de esta forma

2022-12-16 15:27 UTC, josem-perram approved these changes
Simplemente un comentario sobre la navegación con diálogo.

2022-12-16 15:27 UTC, josem-perram commented on app/src/main/res/navigation/nav_graph.xml
> +    <dialog
Méter el action dentro del fragmento donde se usa, el management.

2022-12-20 14:59 UTC, amrubio27 approved these changes
✌ genial joel!. soy yo, o habia muchos archivos en esta PR? 🍻

2023-01-09 18:12 UTC, merged