Issue2 rssmanagment data
Joelgh1/agregador-rss pull request #7
Opened 2022-11-18 15:19 UTC by Joelgh1

## Description de la tarea

Crear la capa de datos para la funcionalidad guardar rss
#3 

## ¿Cómo se ha implementado?

El repositorio implementa los métdos getAll y create para cumplir las funciones que se piden en el ticket. Las funciones son suspendidas porque el ticket pedía corrutinas, al usar shared preferences para el almacenamiento no son necesarias.
He decidido utilizar shared preferences porque los datos que vamos a guardar son mínimos y crear una base de datos solo para dos atributos me parecía excesivo. Las he implementado a nivel de aplicación porque la vista del feed necesitara acceso a las urls para obtener la información.
He usado el nombre como id para almacenar los rss porque considero que no debería haber rss con el mismo nombre, podría ser confuso para el usuario.
He abstraído la librería de serialización gson para evitar esparcirla por la aplicación innecesariamente. De esta forma puede sustituirse por otra de forma sencilla y modificando mínimamente el código.
Implemente either para la gestión de errores y lo utilizo en el metodo getAll, ya que el usuario es el que se encarga de introducir los rss puede que no haya añadido ninguno antes de consultarlos y esto debería ser tratado para no mostrar una pantalla en blanco sin información.

En las capturas se muestra el fichero de shared preferences con información y el resultado que devuelve el repositorio tanto en caso de error como en caso de que tenga información.

## Keywords

capa de datos, either, gestión de errores, corrutinas, shared preferences, local source

## Screenshots or Video

![Captura de pantalla 2022-11-16 165210](https://user-images.githubusercontent.com/107778199/202731459-d5138c41-c7eb-43f5-a444-13e2eb50ea25.png)

![image](https://user-images.githubusercontent.com/107778199/202735052-4575a473-e6d2-430e-8b24-da512ada7247.png)

![image](https://user-images.githubusercontent.com/107778199/202735364-5cfb2b97-1287-4645-9c9c-e1ecf37f70aa.png)

## Objetivos

## Criterios de Evaluación

2022-11-18 15:54 UTC, albertoh8 approved these changes
Muy bien documentada la pr, todo ok

2022-11-30 23:01 UTC, josem-perram requested changes
Joel, revisa comentarios y fíjate en los checks del tickets asociado. @albertoh8 please, revisa los comentarios.

2022-11-30 23:01 UTC, jmperezra commented on app/src/main/java/com/joelgh/features/rss_management/data/RssDataRepository.kt
> +    override suspend fun create(rss: Rss) = localSource.create(rss)
@Joelgh1 en el ticket se indica los parámetros que se reciben del caso de uso. Vamos a tener en cuenta que los modelos de dominio los crea la capa de datos.

2022-11-30 23:01 UTC, jmperezra commented on app/src/main/java/com/joelgh/features/rss_management/data/local/XmlLocalDataSource.kt
> +    override suspend fun create(rss: Rss) = sharedPrefs.edit {
@Joelgh1 esta clase guarda datos?? me parece que te falta el apply o el commit

2022-11-30 23:01 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/rss_management/data/local/XmlLocalDataSource.kt
> +            ErrorApp.DataError().left()
Si no existen datos, consideras que se ha producido un error?? quizás sea interesante contemplar el estado "lista vacía" y que la vista pinta un mensaje de que "no hay datos" en vez de mostrar "se ha producido un error".

2022-11-30 23:01 UTC, josem-perram commented on app/src/main/java/com/joelgh/features/rss_management/domain/SaveRssUseCase.kt
>          repository.create(Rss(name, url))
Please, revisa el ticket sobre los parámetros que se pasan al repository.

2022-11-30 23:13 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/data/local/XmlLocalDataSource.kt
> +            ErrorApp.DataError().left()
Me di cuenta por la última pr y ya hice ese cambio

2022-11-30 23:15 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/data/RssDataRepository.kt
> +    override suspend fun create(rss: Rss) = localSource.create(rss)
No me di cuenta de eso, voy a hacer el cambio y volveré a pedir revisión

2022-11-30 23:16 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/data/local/XmlLocalDataSource.kt
> +    override suspend fun create(rss: Rss) = sharedPrefs.edit {
Cuando hice las pruebas sí y durante el proyecto he guardado varias veces datos y también, de todas formas lo revisaré por si acaso

2022-11-30 23:17 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/features/rss_management/domain/SaveRssUseCase.kt
>          repository.create(Rss(name, url))
Ok

2022-12-16 15:21 UTC, josem-perram approved these changes
🚀

2023-01-09 18:06 UTC, merged